---
description: Participate in Phala Network governance using vPHA tokens and Snapshot.
title: Phala Treasury
---


## Current mechanisms <a href="#current-mechanisms" id="current-mechanisms"></a>

### Spending Proposals <a href="#spending-proposals" id="spending-proposals"></a>

The Treasury is also used to fund spending proposals submitted by community members. These need to be approved by the Council and have the goal of developing ideas that give traction to the network, maintaining infrastructure deployment, security operations, and marketing activities, among others.

## Treasury <a href="#treasury" id="treasury"></a>

The Treasury is the community-controlled fund pool collected through transaction fees, slashing, Secure Worker mining rate (20%) , etc. The funds held in the Treasury can be spent by making a spending proposal that, if approved by the Council. 

With Phala Network’s governance now transitioned to Ethereum Layer 1, Treasury management utilizes Snapshot﻿ for decentralized off-chain voting alongside Safe multisig wallets for secure execution of funding decisions.



Treasury fund will be used on (but are not limited to):

* Infrastructure deployment and continued operation.
* Network security operations (monitoring services, continuous auditing).
* Ecosystem provisions (collaborations with friendly chains).
* Marketing activities (advertising, paid features, collaborations).
* Community events and outreach (meetups, pizza parties, hackerspaces).
* Software development (wallets and wallet integration, clients and client upgrades).

The Treasury is ultimately controlled by the Council, and how the funds will be spent is up to their judgment.

The Treasury is funded from different sources:

1. Slashing: When a Secure Worker is slashed for any reason, the slashed amount is sent to the Treasury with a reward going to the entity that reported the validator (another validator). The reward is taken from the slash amount and varies per offense and number of reporters.
2. Transaction fees: A portion of each block’s transaction fees goes to the Treasury, with the remainder going to the block author.
3. 70% of the PHA will be used for Secure Worker Mining, and following the progress of the Phala network, 20% of the mining rewards generated by each block will be used to fund treasury.



## FAQ <a href="#faq" id="faq"></a>

### What prevents the Treasury from being captured by a majority of the Council? <a href="#what-prevents-the-treasury-from-being-captured-by-a-majority-of-the-council" id="what-prevents-the-treasury-from-being-captured-by-a-majority-of-the-council"></a>

The majority of the Council can decide the outcome of a treasury spend proposal. In an adversarial mindset, we may consider the possibility that the Council may at some point go rogue and attempt to steal all of the treasury funds. It is a possibility that the treasury pot becomes so great, that a large financial incentive would present itself.

It is the case on Phala that the Council is composed of mainly well-known members of the community. Remember, the Council is voted in by the token holders, so they must do some campaigning or otherwise be recognized to earn votes. In the scenario of an attack, the Council members would lose their social credibility. Furthermore, members of the Council are usually externally motivated by the proper operation of the chain. This external motivation is either because they run businesses that depend on the chain, or they have direct financial gain (through their holdings) of the token value remaining steady.

Concretely, there are a couple on-chain methods that resist this kind of attack. One, the Council majority may not be the token majority of the chain. This means that the token majority could vote to replace the Council if they attempted this attack - or even reverse the treasury spend. They would do this through a normal referendum. Two, there are time delays to treasury spends. They are only enacted every spend period. This means that there will be some time to observe this attack is taking place. The time delay then allows chain participants time to respond. The response may take the form of governance measures or - in the most extreme cases a liquidation of their holdings and a migration to a minority fork. However, the possibility of this scenario is quite low.
